version: '3.8'

services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    container_name: benchspotter_frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001

  # Backend API
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: benchspotter_backend_dev
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://benchspotter:devpassword@postgres:5432/benchspotter_dev
      - API_PORT=3001
    depends_on:
      - postgres

  # Database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: benchspotter_db_dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=benchspotter_dev
      - POSTGRES_USER=benchspotter
      - POSTGRES_PASSWORD=devpassword
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
